# Generated by Django 6.0 on 2026-03-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Jamoa yetakchisi', max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(upload_to='leaders/')),
            ],
        ),
    ]
